server:
  port: 8136

spring:
  datasource:
    url: jdbc:postgresql://localhost:5418/bookkeeper?currentSchema=account
    username: root
    password: admin
  flyway:
    enabled: true
    baseline-on-migrate: true
