---
Outputs:
  StuffWebAppECRRepository:
    Description: The ECR repository for the web app
    Value: !Ref StuffWebAppECRRepository
    Export:
      Name: StuffWebAppECRRepository
  StuffWebAppECRRepositoryArn:
    Description: The ECR repository ARN for the web app
    Value: !GetAtt StuffWebAppECRRepository.Arn
    Export:
      Name: StuffWebAppECRRepositoryArn

Resources:

  StuffWebAppECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: stuff/web-app

  StuffWebAppArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stuff-artifacts-bucket
