---
Outputs:
  StuffWebAppECRRepository:
    Description: The ECR repository for the web app
    Value: !Ref StuffWebAppECRRepository
    Export:
      Name: StuffWebAppECRRepository
  StuffWebAppECRRepositoryArn:
    Description: The ECR repository ARN for the web app
    Value: !GetAtt StuffWebAppECRRepository.Arn
    Export:
      Name: StuffWebAppECRRepositoryArn
  StuffPipelineTriggerECRRepository:
    Description: The ECR repository for the pipeline trigger
    Value: !Ref StuffPipelineTriggerECRRepository
    Export:
      Name: StuffPipelineTriggerECRRepository
  StuffArtifactsBucketArn:
    Value: !GetAtt StuffWebAppArtifactsBucket.Arn
    Export:
      Name: StuffArtifactsBucketArn
  StuffArtifactsBucketName:
    Value: !Ref StuffWebAppArtifactsBucket
    Export:
      Name: StuffArtifactsBucketName

Resources:
  StuffWebAppECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: stuff/web-app

  StuffPipelineTriggerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: stuff/pipeline-trigger

  # TODO(Johann) should rename this as it should be used by all pipelines
  StuffWebAppArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stuff-artifacts-bucket
