---
Outputs:
  BookkeeperWebAppECRRepository:
    Description: The ECR repository for the web app
    Value: !Ref BookkeeperWebAppECRRepository
    Export:
      Name: BookkeeperWebAppECRRepository
  BookkeeperWebAppECRRepositoryArn:
    Description: The ECR repository ARN for the web app
    Value: !GetAtt BookkeeperWebAppECRRepository.Arn
    Export:
      Name: BookkeeperWebAppECRRepositoryArn
  BookkeeperPipelineTriggerECRRepository:
    Description: The ECR repository for the pipeline trigger
    Value: !Ref BookkeeperPipelineTriggerECRRepository
    Export:
      Name: BookkeeperPipelineTriggerECRRepository
  BookkeeperArtifactsBucketArn:
    Value: !GetAtt BookkeeperWebAppArtifactsBucket.Arn
    Export:
      Name: BookkeeperArtifactsBucketArn
  BookkeeperArtifactsBucketName:
    Value: !Ref BookkeeperWebAppArtifactsBucket
    Export:
      Name: BookkeeperArtifactsBucketName

Resources:
  BookkeeperWebAppECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bookkeeper/web-app

  BookkeeperPipelineTriggerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bookkeeper/pipeline-trigger

  # TODO(Johann) should rename this as it should be used by all pipelines
  BookkeeperWebAppArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bookkeeper-artifacts-bucket
