---
Parameters:
  GitHubOAuthToken:
    Type: String
    NoEcho: true
  GitHubOwner:
    Type: String
    Default: johannfazakas
  GitHubRepo:
    Type: String
    Default: bookkeeper-infra
  GitHubBranch:
    Type: String
    Default: main

Resources:
  WebAppCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: bookkeeper-web-app-code-build
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: web-app/buildspec.yml
      Cache:
        Type: S3
        Location: bookkeeper-artifacts-bucket
      Artifacts:
        Type: CODEPIPELINE
      ServiceRole: !Ref WebAppCodeBuildRole

  WebAppCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: bookkeeper-web-app-code-pipeline
      ArtifactStore:
        Type: S3
        Location: bookkeeper-artifacts-bucket
      RoleArn: !GetAtt
        - WebAppCodePipelineRole
        - Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                PollForSourceChanges: false
                OAuthToken: !Ref GitHubOAuthToken
              OutputArtifacts:
                - Name: source
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref WebAppCodeBuild
              InputArtifacts:
                - Name: source
              OutputArtifacts:
                - Name: build
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: 1
              Configuration:
                ClusterName: bookkeeper-ecs-cluster
                ServiceName: web-app-service
                FileName: imagedefinitions.json
              InputArtifacts:
                - Name: build

  WebAppCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bookkeeper-web-app-code-build-role
      # TODO(Johann) should I put my roles under a specific path?
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: bookkeeper-code-build-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:*
                Resource: arn:aws:s3:::bookkeeper-artifacts-bucket/*
              - Effect: Allow
                Action:
                  - ecr:*
                Resource: !ImportValue BookkeeperWebAppECRRepositoryArn
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'

  WebAppCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bookkeeper-web-app-code-pipeline-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: bookkeeper-web-app-code-pipeline-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: !Sub
                  - ${BucketArn}/*
                  - BucketArn: !ImportValue BookkeeperArtifactsBucketArn
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: '*'
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService: ecs-tasks.amazonaws.com
              - Effect: Allow
                Action:
                  - codebuild:*
                Resource: !GetAtt WebAppCodeBuild.Arn
              - Effect: Allow
                Action:
                  - ecr:*
                Resource: !ImportValue BookkeeperWebAppECRRepositoryArn
              - Effect: Allow
                Action:
                  - ecs:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:*
                Resource: !ImportValue BookkeeperWebAppLoadBalancerArn
