name: bookkeeper-app

services:
  bk_postgres:
    image: postgres:15
    container_name: bk_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookkeeper
    volumes:
      - bookkeeper_api_postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - bookkeeper_network

  bk_user_service:
    container_name: bk_user_service
    depends_on:
      - bk_postgres
    image: bookkeeper/user-service:latest
    ports:
      - 8132:8132
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://bk_postgres/bookkeeper?currentSchema=bk_user
      SPRING_FLYWAY_URL: jdbc:postgresql://bk_postgres:5432/bookkeeper?currentSchema=bk_user
    networks:
      - bookkeeper_network

  bk_account_service:
    container_name: bk_account_service
    depends_on:
      - bk_postgres
    image: bookkeeper/account-service:latest
    ports:
      - 8136:8136
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bk_postgres:5432/bookkeeper?currentSchema=bk_account
      BOOKKEEPER_INTEGRATION_USER-SERVICE_URL: http://bk_user_service:8132
    networks:
      - bookkeeper_network

volumes:
  bookkeeper_api_postgres:

networks:
  bookkeeper_network:
    driver: bridge
