name: bookkeeper-app

services:
  bookkeeper_api_postgres:
    image: "postgres:15"
    ports:
      - "5418:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookkeeper
    volumes:
      - bookkeeper_api_postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  bookkeeper_api_postgres:
