name: bookkeeper-app

services:
  bk_postgres:
    image: "postgres:15"
    container_name: bk_postgres
    ports:
      - "5418:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookkeeper
    volumes:
      - bookkeeper_api_postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - bookkeeper_network

  bk_account_service:
    container_name: bk_account_service
    depends_on:
      - bk_postgres
    image: "bookkeeper/account-service:latest"
    ports:
      - "8136:8136"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bk_postgres:5432/bookkeeper?currentSchema=bk_account
    networks:
      - bookkeeper_network

volumes:
  bookkeeper_api_postgres:

networks:
  bookkeeper_network:
    driver: bridge
