server:
  port: 8132

spring:
  datasource:
    url: jdbc:postgresql://localhost:5418/bookkeeper?currentSchema=user
    username: root
    password: admin
  flyway:
    enabled: true
    baseline-on-migrate: true
