---
AWSTemplateFormatVersion: 2010-09-09

Outputs:
  BookkeeperWebAppECRRepositoryName:
    Description: The ECR repository for the web app
    Value: !Ref BookkeeperWebAppECRRepository
    Export:
      Name: BookkeeperWebAppECRRepositoryName
  BookkeeperApiGatewayECRRepositoryName:
    Description: The ECR repository for the api gateway
    Value: !Ref BookkeeperApiGatewayECRRepository
    Export:
      Name: BookkeeperApiGatewayECRRepositoryName
  BookkeeperUserServiceECRRepositoryName:
    Description: The ECR repository for the user service
    Value: !Ref BookkeeperUserServiceECRRepository
    Export:
      Name: BookkeeperUserServiceECRRepositoryName
  BookkeeperAccountServiceECRRepositoryName:
    Description: The ECR repository for the account service
    Value: !Ref BookkeeperAccountServiceECRRepository
    Export:
      Name: BookkeeperAccountServiceECRRepositoryName
  BookkeeperPipelineTriggerECRRepositoryName:
    Description: The ECR repository for the pipeline trigger
    Value: !Ref BookkeeperPipelineTriggerECRRepository
    Export:
      Name: BookkeeperPipelineTriggerECRRepositoryName
  BookkeeperArtifactsBucketName:
    Value: !Ref BookkeeperArtifactsBucket
    Export:
      Name: BookkeeperArtifactsBucketName

Resources:
  BookkeeperApiGatewayECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bookkeeper/api-gateway

  BookkeeperUserServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bookkeeper/user-service

  BookkeeperAccountServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bookkeeper/account-service

  BookkeeperWebAppECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bookkeeper/web-app

  BookkeeperPipelineTriggerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bookkeeper/pipeline-trigger

  BookkeeperArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bookkeeper-app-artifacts
