---
AWSTemplateFormatVersion: 2010-09-09

Resources:
  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${ArtifactsBucket}/templates/ecs-cluster.yml"
        - ArtifactsBucket: !ImportValue StuffArtifactsBucketName
