---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ECSClusterName:
    Type: String

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName
      CapacityProviders:
        - FARGATE_SPOT
