---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ECSClusterName:
    Type: String
    Default: bookkeeper-ecs-cluster
  WebAppServiceName:
    Type: String
    Default: bookkeeper-web-app-service
  WebAppLoadBalancerName:
    Type: String
    Default: bookkeeper-web-app-alb
  MonolithApiServiceName:
    Type: String
    Default: bookkeeper-monolith-api-service
  MonolithApiLoadBalancerName:
    Type: String
    Default: bookkeeper-monolith-api-alb
  GitHubOAuthToken:
    Type: String
    NoEcho: true
  GitHubOwner:
    Type: String
    Default: johannfazakas
  GitHubRepo:
    Type: String
    Default: bookkeeper
  GitHubBranch:
    Type: String
    Default: main

Resources:
  BookkeeperECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${ArtifactsBucket}/templates/ecs-cluster.yml"
        - ArtifactsBucket: !ImportValue BookkeeperArtifactsBucketName
      Parameters:
        ECSClusterName: !Ref ECSClusterName

  BookkeeperWebAppService:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BookkeeperECSCluster
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${ArtifactsBucket}/templates/web-app-service.yml"
        - ArtifactsBucket: !ImportValue BookkeeperArtifactsBucketName
      Parameters:
        ECSClusterName: !Ref ECSClusterName
        ECSServiceName: !Ref WebAppServiceName
        ECRRepositoryName: !ImportValue BookkeeperWebAppECRRepositoryName
        LoadBalancerName: !Ref WebAppLoadBalancerName

  BookkeeperWebAppPipeline:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BookkeeperECSCluster
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${ArtifactsBucket}/templates/web-app-pipeline.yml"
        - ArtifactsBucket: !ImportValue BookkeeperArtifactsBucketName
      Parameters:
        ArtifactsBucketName: !ImportValue BookkeeperArtifactsBucketName
        ECSClusterName: !Ref ECSClusterName
        ECSServiceName: !Ref WebAppServiceName
        ECRRepositoryName: !ImportValue BookkeeperWebAppECRRepositoryName
        LoadBalancerName: !Ref WebAppLoadBalancerName
        GitHubOAuthToken: !Ref GitHubOAuthToken
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch

  BookkeeperMonolithApiService:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BookkeeperECSCluster
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${ArtifactsBucket}/templates/monolith-api-service.yml"
        - ArtifactsBucket: !ImportValue BookkeeperArtifactsBucketName
      Parameters:
        ECSClusterName: !Ref ECSClusterName
        ECSServiceName: !Ref MonolithApiServiceName
        ECRRepositoryName: !ImportValue BookkeeperMonolithApiECRRepositoryName
        LoadBalancerName: !Ref MonolithApiLoadBalancerName

  BookkeeperMonolithApiPipeline:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BookkeeperECSCluster
    Properties:
      TemplateURL: !Sub
        - "https://s3.amazonaws.com/${ArtifactsBucket}/templates/monolith-api-pipeline.yml"
        - ArtifactsBucket: !ImportValue BookkeeperArtifactsBucketName
      Parameters:
        ArtifactsBucketName: !ImportValue BookkeeperArtifactsBucketName
        ECSClusterName: !Ref ECSClusterName
        ECSServiceName: !Ref MonolithApiServiceName
        ECRRepositoryName: !ImportValue BookkeeperMonolithApiECRRepositoryName
        LoadBalancerName: !Ref MonolithApiLoadBalancerName
        GitHubOAuthToken: !Ref GitHubOAuthToken
        GitHubOwner: !Ref GitHubOwner
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
