---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ECSClusterName:
    Type: String
  ECSServiceName:
    Type: String
  LoadBalancerName:
    Type: String
  ECRRepositoryName:
    Type: String

Resources:
  MonolithApiService:
    Type: AWS::ECS::Service
    DependsOn:
      - MonolithApiLoadBalancerListener
    Properties:
      ServiceName: !Ref ECSServiceName
      Cluster: !Ref ECSClusterName
      TaskDefinition: !Ref MonolithApiTaskDefinition
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: bookkeeper-monolith-api
          ContainerPort: 80
          TargetGroupArn: !GetAtt MonolithApiLoadBalancerTargetGroup.TargetGroupArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt MonolithApiServiceSecurityGroup.GroupId
          # IMPROVE pass subnets as parameters
          Subnets:
            - subnet-03b0f58983b5d5b8a
            - subnet-0910d8975e3dbf48b
            - subnet-0a55796ab32a4156e
      DesiredCount: 2
      SchedulingStrategy: REPLICA
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 200
      DeploymentController:
        Type: ECS

  MonolithApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: bookkeeper-monolith-api
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryName}:latest
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: prod
      ExecutionRoleArn: !GetAtt MonolithApiExecutionRole.Arn
      TaskRoleArn: !GetAtt MonolithApiTaskRole.Arn
      Family: monolith-api
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512

  MonolithApiLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref LoadBalancerName
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - !GetAtt MonolithApiLoadBalancerSecurityGroup.GroupId
      # IMPROVE pass subnet ids as parameters
      Subnets:
        - subnet-03b0f58983b5d5b8a
        - subnet-0910d8975e3dbf48b
        - subnet-0a55796ab32a4156e

  MonolithApiLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: bookkeeper-monolith-api-alb-tg
      Protocol: HTTP
      Port: 80
      # IMPROVE pass vpc id as parameter
      VpcId: vpc-0ae8710521d1b1869
      IpAddressType: ipv4
      TargetType: ip

  MonolithApiLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MonolithApiLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !GetAtt MonolithApiLoadBalancerTargetGroup.TargetGroupArn

  MonolithApiLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: bookkeeper-monolith-api-alb-sg
      GroupDescription: Security group for the monolith-api load balancer
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80

  MonolithApiServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: bookkeeper-monolith-api-service-sg
      GroupDescription: Security group for the monolith-api service
      SecurityGroupIngress:
        - SourceSecurityGroupId: !GetAtt MonolithApiLoadBalancerSecurityGroup.GroupId
          IpProtocol: tcp
          # IMPROVE there should be a way to display * instead of 0-65535
          FromPort: 0
          ToPort: 65535

  MonolithApiExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bookkeeper-monolith-api-task-execution-role
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: bookkeeper-monolith-api-task-execution-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  MonolithApiTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bookkeeper-monolith-api-task-container-role
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: bookkeeper-monolith-api-task-container-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  MonolithApiServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bookkeeper-monolith-api-service-role
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: bookkeeper-monolith-api-task-container-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
