---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ECSClusterName:
    Type: String
  ECSServiceName:
    Type: String
  LoadBalancerName:
    Type: String
  ECRRepositoryName:
    Type: String

Resources:
  AccountServiceService:
    Type: AWS::ECS::Service
    DependsOn:
      - AccountServiceLoadBalancerListener
    Properties:
      ServiceName: !Ref ECSServiceName
      Cluster: !Ref ECSClusterName
      TaskDefinition: !Ref AccountServiceTaskDefinition
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: bookkeeper-account-service
          ContainerPort: 80
          TargetGroupArn: !GetAtt AccountServiceLoadBalancerTargetGroup.TargetGroupArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt AccountServiceServiceSecurityGroup.GroupId
          # IMPROVE pass subnets as parameters
          Subnets:
            - subnet-03b0f58983b5d5b8a
            - subnet-0910d8975e3dbf48b
            - subnet-0a55796ab32a4156e
      DesiredCount: 2
      SchedulingStrategy: REPLICA
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 200
      DeploymentController:
        Type: ECS

  AccountServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: bookkeeper-account-service
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryName}:latest
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: prod
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /bookkeeper/ecs/account-service
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: bookkeeper-prefix
      ExecutionRoleArn: !GetAtt AccountServiceExecutionRole.Arn
      TaskRoleArn: !GetAtt AccountServiceTaskRole.Arn
      Family: account-service
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512

  AccountServiceLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref LoadBalancerName
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - !GetAtt AccountServiceLoadBalancerSecurityGroup.GroupId
      # IMPROVE pass subnet ids as parameters
      Subnets:
        - subnet-03b0f58983b5d5b8a
        - subnet-0910d8975e3dbf48b
        - subnet-0a55796ab32a4156e

  AccountServiceLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: bookkeeper-account-service-alb-tg
      Protocol: HTTP
      Port: 80
      HealthCheckPath: /actuator/health
      # IMPROVE pass vpc id as parameter
      VpcId: vpc-0ae8710521d1b1869
      IpAddressType: ipv4
      TargetType: ip

  AccountServiceLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref AccountServiceLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !GetAtt AccountServiceLoadBalancerTargetGroup.TargetGroupArn

  AccountServiceLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: bookkeeper-account-service-alb-sg
      GroupDescription: Security group for the account-service load balancer
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80

  AccountServiceServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: bookkeeper-account-service-service-sg
      GroupDescription: Security group for the account-service service
      SecurityGroupIngress:
        - SourceSecurityGroupId: !GetAtt AccountServiceLoadBalancerSecurityGroup.GroupId
          IpProtocol: tcp
          # IMPROVE there should be a way to display * instead of 0-65535
          FromPort: 0
          ToPort: 65535

  AccountServiceExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bookkeeper-account-service-task-execution-role
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: bookkeeper-account-service-task-execution-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  AccountServiceTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bookkeeper-account-service-task-container-role
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: bookkeeper-account-service-task-container-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  AccountServiceServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bookkeeper-account-service-service-role
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: bookkeeper-account-service-task-container-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
