---
AWSTemplateFormatVersion: 2010-09-09

Outputs:
  BookkeeperWebAppECRRepositoryName:
    Description: The ECR repository for the web app
    Value: !Ref BookkeeperWebAppECRRepository
    Export:
      Name: BookkeeperWebAppECRRepositoryName
  BookkeeperPipelineTriggerECRRepositoryName:
    Description: The ECR repository for the pipeline trigger
    Value: !Ref BookkeeperPipelineTriggerECRRepository
    Export:
      Name: BookkeeperPipelineTriggerECRRepositoryName
  BookkeeperArtifactsBucketName:
    Value: !Ref BookkeeperArtifactsBucket
    Export:
      Name: BookkeeperArtifactsBucketName

Resources:
  BookkeeperWebAppECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bookkeeper/web-app

  BookkeeperPipelineTriggerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bookkeeper/pipeline-trigger

  BookkeeperArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bookkeeper-artifacts
