ktor:
  application:
    modules:
      - ro.jf.bk.apigw.BookkeeperApiGatewayKt.module
  deployment:
    port: 8101

bookkeeper:
  integration:
    user-service:
      url: "$USER_SERVICE_URL:http://localhost:8132"
    account-service:
      url: "$ACCOUNT_SERVICE_URL:http://localhost:8136"
